"""
Language-aware document labels.

Provides section headings for Word and PDF documents in all supported languages.
RTL languages (Hebrew, Arabic) are marked for proper text direction handling.
"""

from typing import TypedDict


class DocumentLabels(TypedDict):
    """Document section labels in a specific language."""
    title: str
    transcript: str
    summary: str
    participants: str
    decisions: str
    actions: str
    owner: str
    unassigned: str
    none: str
    generated_by: str


# RTL (Right-to-Left) languages
RTL_LANGUAGES: frozenset[str] = frozenset({"he", "ar"})


def is_rtl(language: str) -> bool:
    """Check if a language uses RTL text direction."""
    return language.lower() in RTL_LANGUAGES


# Document labels for all supported languages
DOCUMENT_LABELS: dict[str, DocumentLabels] = {
    "en": {
        "title": "Meeting Summary",
        "transcript": "Transcript",
        "summary": "Summary",
        "participants": "Participants",
        "decisions": "Decisions",
        "actions": "Action Items",
        "owner": "Owner",
        "unassigned": "Unassigned",
        "none": "None",
        "generated_by": "Generated by Speechi",
    },
    "he": {
        "title": "סיכום פגישה",
        "transcript": "תמלול",
        "summary": "תקציר",
        "participants": "משתתפים",
        "decisions": "החלטות",
        "actions": "משימות לביצוע",
        "owner": "אחראי",
        "unassigned": "לא שויך",
        "none": "אין",
        "generated_by": "נוצר על ידי Speechi",
    },
    "fr": {
        "title": "Résumé de réunion",
        "transcript": "Transcription",
        "summary": "Résumé",
        "participants": "Participants",
        "decisions": "Décisions",
        "actions": "Actions à réaliser",
        "owner": "Responsable",
        "unassigned": "Non assigné",
        "none": "Aucun",
        "generated_by": "Généré par Speechi",
    },
    "es": {
        "title": "Resumen de reunión",
        "transcript": "Transcripción",
        "summary": "Resumen",
        "participants": "Participantes",
        "decisions": "Decisiones",
        "actions": "Tareas pendientes",
        "owner": "Responsable",
        "unassigned": "Sin asignar",
        "none": "Ninguno",
        "generated_by": "Generado por Speechi",
    },
    "ar": {
        "title": "ملخص الاجتماع",
        "transcript": "النص",
        "summary": "الملخص",
        "participants": "المشاركون",
        "decisions": "القرارات",
        "actions": "المهام المطلوبة",
        "owner": "المسؤول",
        "unassigned": "غير معين",
        "none": "لا يوجد",
        "generated_by": "تم الإنشاء بواسطة Speechi",
    },
}


def get_labels(language: str) -> DocumentLabels:
    """
    Get document labels for a specific language.
    
    Args:
        language: ISO 639-1 language code (en, he, fr, es, ar).
        
    Returns:
        DocumentLabels for the specified language, defaults to English if not found.
    """
    return DOCUMENT_LABELS.get(language.lower(), DOCUMENT_LABELS["en"])
